configs:
  codel_on:
    file: ceph.conf
    section: global
    values:
      bluestore codel: true
      bluestore codel throughput latency tradeoff: {0}
      bluestore codel initial target latency: 5
      bluestore codel fast interval: 50
      bluestore codel slow interval: 500
      bluestore codel initial budget bytes: 256Ki
      bluestore codel min budget bytes: {1}
      bluestore codel max target latency: 1000
      bluestore codel min target latency: 1
      bluestore codel regression history size: 100
      bluestore codel budget increment bytes: {2}
  codel_off:
    file: ceph.conf
    section: global
    values:
      bluestore codel: false
  mclock:
    file: ceph.conf
    section: global
    values:
      osd op queue: mclock_scheduler
      osd mclock skip benchmark: true
  wpq:
    file: ceph.conf
    section: global
    values:
      osd op queue: wpq
  mclock_client_profile:
    file: ceph.conf
    section: global
    values:
      osd mclock scheduler client res: {0}
      osd mclock scheduler client wgt: {1}
      osd mclock scheduler client lim: {2}
  mclock_recov_profile:
    file: ceph.conf
    section: global
    values:
      osd mclock scheduler background recovery res: {0}
      osd mclock scheduler background recovery wgt: {1}
      osd mclock scheduler background recovery lim: {2}
  sharding_off:
    file: ceph.conf
    section: global
    values:
      osd op num shards: 1
  sharding_on:
    file: ceph.conf
    section: global
    values:
      osd op num shards: {0}
  throttle_off:
    file: ceph.conf
    section: global
    values:
      bluestore throttle bytes: 10240Mi
      bluestore throttle deferred_bytes: 10240Mi
  throttle_on:
    file: ceph.conf
    section: global
    values:
      bluestore throttle bytes: {0}
      bluestore throttle deferred_bytes: {0}
  fio_regular:
    file: cbt.yaml
    section: benchmarks
    sub_section: fio
    values:
      iodepth: {0}
  fio_burst:
    file: cbt.yaml
    section: benchmarks
    sub_section: fio
    values:
      iodepth: {0}
      thinktime: {1}
      thinktime_blocks: {0}
      iodepth_low: 0
      iodepth_batch_submit: 0
      iodepth_batch_complete_min: 1
      iodepth_batch_complete_max: {0}
  fio_bs:
    file: cbt.yaml
    section: benchmarks
    sub_section: fio
    values:
      op_size: {0}
  recovery_off:
    file: cbt.yaml
    section: cluster
    sub_section: recovery_test
    values:
      osds: []

benchmarks:
  - name: mclock_no_control_no_recovery
    configs:
      - name: codel_off
        params: []
      - name: mclock
        params: []
      - name: sharding_off
        params: []
      - name: mclock_client_profile
        params: [9000,2,1000000]
      - name: mclock_recov_profile
        params: [100,1,1000000]
      - name: throttle_off
        params: []
      - name: recovery_off
        params: []
      - name:
        params: [ ]
      - name:
        params: [ ]
      - name:
        params: [ ]
      - name:
        params: [ ]

  - name: codel_mclock
    configs:
      - name: codel_on
        params: [1, 256Ki, 50Ki]
      - name: mclock
        params: []
      - name: mclock_client_profile
        params: []
      - name: mclock_recov_profile
        params: []
      - name: sharding_off
        params: []
      - name:
        params: []
      - name:
        params: []
      - name:
        params: []
      - name:
        params: []
  - name:
    configs:
      - name:
        params: []