variables:
  client_iops: 20000
  recovery_iops: 1
  client_wgt: 2
  recovery_wgt: 1
  client_limit: 1000000
  recovery_limit: 1000000
  burst_time: 1s

configs:
  codel_on:
    file: ceph.conf
    section: [global]
    values:
      bluestore codel: true
      bluestore codel throughput latency tradeoff: {0}
      bluestore codel initial target latency: 5
      bluestore codel fast interval: 50
      bluestore codel slow interval: 500
      bluestore codel initial budget bytes: {1}
      bluestore codel min budget bytes: {1}
      bluestore codel max target latency: 1000
      bluestore codel min target latency: 1
      bluestore codel regression history size: 20
      bluestore codel budget increment bytes: {2}
  codel_off:
    file: ceph.conf
    section: [global]
    values:
      bluestore codel: false
  mclock:
    file: ceph.conf
    section: [global]
    values:
      osd op queue: mclock_scheduler
      osd mclock skip benchmark: true
  wpq:
    file: ceph.conf
    section: [global]
    values:
      osd op queue: wpq
  mclock_client_profile:
    file: ceph.conf
    section: [global]
    values:
      osd mclock scheduler client res: {0}
      osd mclock scheduler client wgt: {1}
      osd mclock scheduler client lim: {2}
  mclock_recov_profile:
    file: ceph.conf
    section: [global]
    values:
      osd mclock scheduler background recovery res: {0}
      osd mclock scheduler background recovery wgt: {1}
      osd mclock scheduler background recovery lim: {2}
  sharding_off:
    file: ceph.conf
    section: [global]
    values:
      osd op num shards: 1
  sharding_on:
    file: ceph.conf
    section: [global]
    values:
      osd op num shards: {0}
  throttle_off:
    file: ceph.conf
    section: [global]
    values:
      bluestore throttle bytes: 10240Mi
      bluestore throttle deferred_bytes: 10240Mi
  throttle_on:
    file: ceph.conf
    section: [global]
    values:
      bluestore throttle bytes: {0}
      bluestore throttle deferred_bytes: {0}
  fio:
    file: cbt.yaml
    section: [benchmarks, fio]
    values:
      op_size: {0}
      iodepth: {1}
  fio_burst:
    file: cbt.yaml
    section: [benchmarks, fio, extra_config]
    values:
      thinktime: {0}
      thinktime_blocks: {1}
      iodepth_low: 0
      iodepth_batch_submit: 0
      iodepth_batch_complete_min: 1
      iodepth_batch_complete_max: {1}
  recovery_on:
    file: cbt.yaml
    section: [cluster, recovery_test]
    values:
      osds: [1]
  recovery_size:
    file: cbt.yaml
    section: [ cluster, pool_profiles, rbdrecov ]
    values:
      prefill_recov_object_size: {0}
