benchmarks:
  # why dynamic throttle
  - name: no_control_4k_64
    configs:
      - name: codel_off
        params: []
      - name: mclock
        params: []
      - name: sharding_off
        params: []
      - name: mclock_client_profile
        params: [ $client_iops, $client_wgt, $client_limit ]
      - name: mclock_recov_profile
        params: [ $recovery_iops, $recovery_wgt, $recovery_limit ]
      - name: throttle_off
        params: []
      - name: fio
        params: [4Ki, 64]
  - name: no_control_32k_64
    configs:
      - name: codel_off
        params: []
      - name: mclock
        params: []
      - name: sharding_off
        params: []
      - name: mclock_client_profile
        params: [ $client_iops, $client_wgt, $client_limit ]
      - name: mclock_recov_profile
        params: [ $recovery_iops, $recovery_wgt, $recovery_limit ]
      - name: throttle_off
        params: []
      - name: fio
        params: [32Ki, 64]
  - name: no_control_64k_64
    configs:
      - name: codel_off
        params: []
      - name: mclock
        params: []
      - name: sharding_off
        params: []
      - name: mclock_client_profile
        params: [ $client_iops, $client_wgt, $client_limit ]
      - name: mclock_recov_profile
        params: [ $recovery_iops, $recovery_wgt, $recovery_limit ]
      - name: throttle_off
        params: []
      - name: fio
        params: [64Ki, 64]
  - name: no_control_4k_1024
    configs:
      - name: codel_off
        params: []
      - name: mclock
        params: []
      - name: sharding_off
        params: []
      - name: mclock_client_profile
        params: [ $client_iops, $client_wgt, $client_limit ]
      - name: mclock_recov_profile
        params: [ $recovery_iops, $recovery_wgt, $recovery_limit ]
      - name: throttle_off
        params: []
      - name: fio
        params: [4Ki, 1024]
  - name: no_control_32k_1024
    configs:
      - name: codel_off
        params: []
      - name: mclock
        params: []
      - name: sharding_off
        params: []
      - name: mclock_client_profile
        params: [ $client_iops, $client_wgt, $client_limit ]
      - name: mclock_recov_profile
        params: [ $recovery_iops, $recovery_wgt, $recovery_limit ]
      - name: throttle_off
        params: []
      - name: fio
        params: [32Ki, 1024]
  - name: no_control_64k_1024
    configs:
      - name: codel_off
        params: []
      - name: mclock
        params: []
      - name: sharding_off
        params: []
      - name: mclock_client_profile
        params: [ $client_iops, $client_wgt, $client_limit ]
      - name: mclock_recov_profile
        params: [ $recovery_iops, $recovery_wgt, $recovery_limit ]
      - name: throttle_off
        params: []
      - name: fio
        params: [64Ki, 1024]
  # why throttle no recovery
  - name: no_control_4k_64_burst
    configs:
      - name: codel_off
        params: []
      - name: mclock
        params: []
      - name: sharding_off
        params: []
      - name: mclock_client_profile
        params: [ $client_iops, $client_wgt, $client_limit ]
      - name: mclock_recov_profile
        params: [ $recovery_iops, $recovery_wgt, $recovery_limit ]
      - name: throttle_off
        params: []
      - name: fio
        params: [4Ki, 64]
      - name: fio_burst
        params: [ $burst_time, 64]
  - name: no_control_32k_64_burst
    configs:
      - name: codel_off
        params: []
      - name: mclock
        params: []
      - name: sharding_off
        params: []
      - name: mclock_client_profile
        params: [ $client_iops, $client_wgt, $client_limit ]
      - name: mclock_recov_profile
        params: [ $recovery_iops, $recovery_wgt, $recovery_limit ]
      - name: throttle_off
        params: []
      - name: fio
        params: [32Ki, 64]
      - name: fio_burst
        params: [ $burst_time, 64]
  - name: no_control_4k_1024_burst
    configs:
      - name: codel_off
        params: []
      - name: mclock
        params: []
      - name: sharding_off
        params: []
      - name: mclock_client_profile
        params: [ $client_iops, $client_wgt, $client_limit ]
      - name: mclock_recov_profile
        params: [ $recovery_iops, $recovery_wgt, $recovery_limit ]
      - name: throttle_off
        params: []
      - name: fio
        params: [4Ki, 1024]
      - name: fio_burst
        params: [ $burst_time, 1024]
  - name: no_control_32k_1024_burst
    configs:
      - name: codel_off
        params: []
      - name: mclock
        params: []
      - name: sharding_off
        params: []
      - name: mclock_client_profile
        params: [ $client_iops, $client_wgt, $client_limit ]
      - name: mclock_recov_profile
        params: [ $recovery_iops, $recovery_wgt, $recovery_limit ]
      - name: throttle_off
        params: []
      - name: fio
        params: [32Ki, 1024]
      - name: fio_burst
        params: [ $burst_time, 1024]
  # why throttle recovery 10k
  - name: no_control_4k_64_burst_recov_10k
    configs:
      - name: codel_off
        params: []
      - name: mclock
        params: []
      - name: sharding_off
        params: []
      - name: mclock_client_profile
        params: [ $client_iops, $client_wgt, $client_limit ]
      - name: mclock_recov_profile
        params: [ $recovery_iops, $recovery_wgt, $recovery_limit ]
      - name: throttle_off
        params: []
      - name: fio
        params: [4Ki, 64]
      - name: fio_burst
        params: [ $burst_time, 64]
      - name: recovery_on
        params: []
      - name: recovery_size
        params: [ 10240 ]
  - name: no_control_32k_64_burst_recov_10k
    configs:
      - name: codel_off
        params: []
      - name: mclock
        params: []
      - name: sharding_off
        params: []
      - name: mclock_client_profile
        params: [ $client_iops, $client_wgt, $client_limit ]
      - name: mclock_recov_profile
        params: [ $recovery_iops, $recovery_wgt, $recovery_limit ]
      - name: throttle_off
        params: []
      - name: fio
        params: [32Ki, 64]
      - name: fio_burst
        params: [ $burst_time, 64]
      - name: recovery_on
        params: []
      - name: recovery_size
        params: [ 10240 ]
  - name: no_control_4k_1024_burst_recov_10k
    configs:
      - name: codel_off
        params: []
      - name: mclock
        params: []
      - name: sharding_off
        params: []
      - name: mclock_client_profile
        params: [ $client_iops, $client_wgt, $client_limit ]
      - name: mclock_recov_profile
        params: [ $recovery_iops, $recovery_wgt, $recovery_limit ]
      - name: throttle_off
        params: []
      - name: fio
        params: [4Ki, 1024]
      - name: fio_burst
        params: [ $burst_time, 1024]
      - name: recovery_on
        params: []
      - name: recovery_size
        params: [ 10240 ]
  - name: no_control_32k_1024_burst_recov_10k
    configs:
      - name: codel_off
        params: []
      - name: mclock
        params: []
      - name: sharding_off
        params: []
      - name: mclock_client_profile
        params: [ $client_iops, $client_wgt, $client_limit ]
      - name: mclock_recov_profile
        params: [ $recovery_iops, $recovery_wgt, $recovery_limit ]
      - name: throttle_off
        params: []
      - name: fio
        params: [32Ki, 1024]
      - name: fio_burst
        params: [ $burst_time, 1024]
      - name: recovery_on
        params: []
      - name: recovery_size
        params: [ 10240 ]
  # why throttle recovery 40k
  - name: no_control_4k_64_burst_recov_40k
    configs:
      - name: codel_off
        params: []
      - name: mclock
        params: []
      - name: sharding_off
        params: []
      - name: mclock_client_profile
        params: [ $client_iops, $client_wgt, $client_limit ]
      - name: mclock_recov_profile
        params: [ $recovery_iops, $recovery_wgt, $recovery_limit ]
      - name: throttle_off
        params: []
      - name: fio
        params: [4Ki, 64]
      - name: fio_burst
        params: [ $burst_time, 64]
      - name: recovery_on
        params: []
      - name: recovery_size
        params: [ 40960 ]
  - name: no_control_32k_64_burst_recov_40k
    configs:
      - name: codel_off
        params: []
      - name: mclock
        params: []
      - name: sharding_off
        params: []
      - name: mclock_client_profile
        params: [ $client_iops, $client_wgt, $client_limit ]
      - name: mclock_recov_profile
        params: [ $recovery_iops, $recovery_wgt, $recovery_limit ]
      - name: throttle_off
        params: []
      - name: fio
        params: [32Ki, 64]
      - name: fio_burst
        params: [ $burst_time, 64]
      - name: recovery_on
        params: []
      - name: recovery_size
        params: [ 40960 ]
  - name: no_control_4k_1024_burst_recov_40k
    configs:
      - name: codel_off
        params: []
      - name: mclock
        params: []
      - name: sharding_off
        params: []
      - name: mclock_client_profile
        params: [ $client_iops, $client_wgt, $client_limit ]
      - name: mclock_recov_profile
        params: [ $recovery_iops, $recovery_wgt, $recovery_limit ]
      - name: throttle_off
        params: []
      - name: fio
        params: [4Ki, 1024]
      - name: fio_burst
        params: [ $burst_time, 1024]
      - name: recovery_on
        params: []
      - name: recovery_size
        params: [ 40960 ]
  - name: no_control_32k_1024_burst_recov_40k
    configs:
      - name: codel_off
        params: []
      - name: mclock
        params: []
      - name: sharding_off
        params: []
      - name: mclock_client_profile
        params: [ $client_iops, $client_wgt, $client_limit ]
      - name: mclock_recov_profile
        params: [ $recovery_iops, $recovery_wgt, $recovery_limit ]
      - name: throttle_off
        params: []
      - name: fio
        params: [32Ki, 1024]
      - name: fio_burst
        params: [ $burst_time, 1024]
      - name: recovery_on
        params: []
      - name: recovery_size
        params: [ 40960 ]
  # why throttle recovery 4m
  - name: no_control_4k_64_burst_recov_4m
    configs:
      - name: codel_off
        params: []
      - name: mclock
        params: []
      - name: sharding_off
        params: []
      - name: mclock_client_profile
        params: [ $client_iops, $client_wgt, $client_limit ]
      - name: mclock_recov_profile
        params: [ $recovery_iops, $recovery_wgt, $recovery_limit ]
      - name: throttle_off
        params: []
      - name: fio
        params: [4Ki, 64]
      - name: fio_burst
        params: [ $burst_time, 64]
      - name: recovery_on
        params: []
      - name: recovery_size
        params: [ 4194304 ]
  - name: no_control_32k_64_burst_recov_4m
    configs:
      - name: codel_off
        params: []
      - name: mclock
        params: []
      - name: sharding_off
        params: []
      - name: mclock_client_profile
        params: [ $client_iops, $client_wgt, $client_limit ]
      - name: mclock_recov_profile
        params: [ $recovery_iops, $recovery_wgt, $recovery_limit ]
      - name: throttle_off
        params: []
      - name: fio
        params: [32Ki, 64]
      - name: fio_burst
        params: [ $burst_time, 64]
      - name: recovery_on
        params: []
      - name: recovery_size
        params: [ 4194304 ]
  - name: no_control_4k_1024_burst_recov_4m
    configs:
      - name: codel_off
        params: []
      - name: mclock
        params: []
      - name: sharding_off
        params: []
      - name: mclock_client_profile
        params: [ $client_iops, $client_wgt, $client_limit ]
      - name: mclock_recov_profile
        params: [ $recovery_iops, $recovery_wgt, $recovery_limit ]
      - name: throttle_off
        params: []
      - name: fio
        params: [4Ki, 1024]
      - name: fio_burst
        params: [ $burst_time, 1024]
      - name: recovery_on
        params: []
      - name: recovery_size
        params: [ 4194304 ]
  - name: no_control_32k_1024_burst_recov_4m
    configs:
      - name: codel_off
        params: []
      - name: mclock
        params: []
      - name: sharding_off
        params: []
      - name: mclock_client_profile
        params: [ $client_iops, $client_wgt, $client_limit ]
      - name: mclock_recov_profile
        params: [ $recovery_iops, $recovery_wgt, $recovery_limit ]
      - name: throttle_off
        params: []
      - name: fio
        params: [32Ki, 1024]
      - name: fio_burst
        params: [ $burst_time, 1024]
      - name: recovery_on
        params: []
      - name: recovery_size
        params: [ 4194304 ]