benchmarks:
  - name: static_ac_${var}_4k_64_burst_recov_300k_high_client
    vars: <!['8Ki', '64Ki', '128Ki', '256Ki', '384Ki', '512Ki', '640Ki', '768Ki', '896Ki', '1024Ki', '1152Ki', '1280Ki', '1408Ki', '1536Ki', '1664Ki', '1792Ki', '1920Ki', '2048Ki', '4096Ki', '8192Ki', '65536Ki']!>
    configs:
      - name: codel_off
        params: [ ]
      - name: mclock
        params: [ ]
      - name: sharding_off
        params: [ ]
      - name: mclock_profile
        params: [ high_client_ops ]
      - name: throttle_on
        params: [ $var ]
      - name: fio
        params: [ 4Ki, 64 ]
      - name: fio_burst
        params: [ $burst_time, 64]
      - name: recovery_on
        params: [ ]
      - name: recovery_size
        params: [ 300Ki ]
  - name: static_ac_${var}_4k_64_burst_recov_300k_high_recov
    vars: <!['8Ki', '64Ki', '128Ki', '256Ki', '384Ki', '512Ki', '640Ki', '768Ki', '896Ki', '1024Ki', '1152Ki', '1280Ki', '1408Ki', '1536Ki', '1664Ki', '1792Ki', '1920Ki', '2048Ki', '4096Ki', '8192Ki', '65536Ki']!>
    configs:
      - name: codel_off
        params: [ ]
      - name: mclock
        params: [ ]
      - name: sharding_off
        params: [ ]
      - name: mclock_profile
        params: [ high_recovery_ops ]
      - name: throttle_on
        params: [ $var ]
      - name: fio
        params: [ 4Ki, 64 ]
      - name: fio_burst
        params: [ $burst_time, 64]
      - name: recovery_on
        params: [ ]
      - name: recovery_size
        params: [ 300Ki ]