benchmarks:
- name: static_ac_${var}_4Ki_100:32Ki_0_64_burst_recov_300k
    vars: <!['8Ki', '64Ki', '128Ki', '256Ki', '384Ki', '512Ki', '640Ki', '768Ki', '896Ki', '1024Ki', '1152Ki', '1280Ki', '1408Ki', '1536Ki', '1664Ki', '1792Ki', '1920Ki', '2048Ki', '4096Ki', '8192Ki', '65536Ki']!>
    configs:
      - name: codel_off
        params: [ ]
      - name: mclock
        params: [ ]
      - name: sharding_off
        params: [ ]
      - name: mclock_client_profile
        params: [ $client_iops, $client_wgt, $client_limit ]
      - name: mclock_recov_profile
        params: [ $recovery_iops, $recovery_wgt, $recovery_limit ]
      - name: throttle_on
        params: [ $var ]
      - name: fio
        params: [ 4Ki, 64 ]
      - name: fio_burst
        params: [ $burst_time, 64]
      - name: recovery_on
        params: [ ]
      - name: recovery_size
        params: [ 300Ki ]
- name: static_ac_${var}_4Ki_0:32Ki_100_64_burst_recov_300k
    vars: <!['8Ki', '64Ki', '128Ki', '256Ki', '384Ki', '512Ki', '640Ki', '768Ki', '896Ki', '1024Ki', '1152Ki', '1280Ki', '1408Ki', '1536Ki', '1664Ki', '1792Ki', '1920Ki', '2048Ki', '4096Ki', '8192Ki', '65536Ki']!>
    configs:
      - name: codel_off
        params: [ ]
      - name: mclock
        params: [ ]
      - name: sharding_off
        params: [ ]
      - name: mclock_client_profile
        params: [ $client_iops, $client_wgt, $client_limit ]
      - name: mclock_recov_profile
        params: [ $recovery_iops, $recovery_wgt, $recovery_limit ]
      - name: throttle_on
        params: [ $var ]
      - name: fio
        params: [ 32Ki, 64 ]
      - name: fio_burst
        params: [ $burst_time, 64]
      - name: recovery_on
        params: [ ]
      - name: recovery_size
        params: [ 300Ki ]
- name: static_ac_${var}_4Ki_75:32Ki_25_64_burst_recov_300k
    vars: <!['8Ki', '64Ki', '128Ki', '256Ki', '384Ki', '512Ki', '640Ki', '768Ki', '896Ki', '1024Ki', '1152Ki', '1280Ki', '1408Ki', '1536Ki', '1664Ki', '1792Ki', '1920Ki', '2048Ki', '4096Ki', '8192Ki', '65536Ki']!>
    configs:
      - name: codel_off
        params: [ ]
      - name: mclock
        params: [ ]
      - name: sharding_off
        params: [ ]
      - name: mclock_client_profile
        params: [ $client_iops, $client_wgt, $client_limit ]
      - name: mclock_recov_profile
        params: [ $recovery_iops, $recovery_wgt, $recovery_limit ]
      - name: throttle_on
        params: [ $var ]
      - name: fio_mixed_write
        params: [ 4Ki/75:32Ki/25, 64 ]
      - name: fio_burst
        params: [ $burst_time, 64]
      - name: recovery_on
        params: [ ]
      - name: recovery_size
        params: [ 300Ki ]
- name: static_ac_${var}_4Ki_50:32Ki_50_64_burst_recov_300k
    vars: <!['8Ki', '64Ki', '128Ki', '256Ki', '384Ki', '512Ki', '640Ki', '768Ki', '896Ki', '1024Ki', '1152Ki', '1280Ki', '1408Ki', '1536Ki', '1664Ki', '1792Ki', '1920Ki', '2048Ki', '4096Ki', '8192Ki', '65536Ki']!>
    configs:
      - name: codel_off
        params: [ ]
      - name: mclock
        params: [ ]
      - name: sharding_off
        params: [ ]
      - name: mclock_client_profile
        params: [ $client_iops, $client_wgt, $client_limit ]
      - name: mclock_recov_profile
        params: [ $recovery_iops, $recovery_wgt, $recovery_limit ]
      - name: throttle_on
        params: [ $var ]
      - name: fio_mixed_write
        params: [ 4Ki/50:32Ki/50, 64 ]
      - name: fio_burst
        params: [ $burst_time, 64]
      - name: recovery_on
        params: [ ]
      - name: recovery_size
        params: [ 300Ki ]
- name: static_ac_${var}_4Ki_25:32Ki_75_64_burst_recov_300k
    vars: <!['8Ki', '64Ki', '128Ki', '256Ki', '384Ki', '512Ki', '640Ki', '768Ki', '896Ki', '1024Ki', '1152Ki', '1280Ki', '1408Ki', '1536Ki', '1664Ki', '1792Ki', '1920Ki', '2048Ki', '4096Ki', '8192Ki', '65536Ki']!>
    configs:
      - name: codel_off
        params: [ ]
      - name: mclock
        params: [ ]
      - name: sharding_off
        params: [ ]
      - name: mclock_client_profile
        params: [ $client_iops, $client_wgt, $client_limit ]
      - name: mclock_recov_profile
        params: [ $recovery_iops, $recovery_wgt, $recovery_limit ]
      - name: throttle_on
        params: [ $var ]
      - name: fio_mixed_write
        params: [ 4Ki/25:32Ki/75, 64 ]
      - name: fio_burst
        params: [ $burst_time, 64]
      - name: recovery_on
        params: [ ]
      - name: recovery_size
        params: [ 300Ki ]
