variables:
  client_iops: 0.9
  recovery_iops: 0.1
  client_wgt: 2
  recovery_wgt: 1
  client_limit: 0
  recovery_limit: 0
  burst_time: 1s
  codel_param: 0.1,
  codel_budget: 256Ki
  codel_inc: 10Ki
  recover_size1: 300Ki
  recover_size2: 16Ki


configs:
  codel_on:
    dependencies: [ ]
    file: ceph.conf
    section: [ global ]
    values:
      bluestore codel: true
      bluestore codel throughput latency tradeoff: { 0 }
      bluestore codel initial target latency: 5
      bluestore codel fast interval: 50
      bluestore codel slow interval: 500
      bluestore codel initial budget bytes: { 1 }
      bluestore codel min budget bytes: { 1 }
      bluestore codel max target latency: 1000
      bluestore codel min target latency: 1
      bluestore codel regression history size: 100
      bluestore codel budget increment bytes: { 2 }
  codel_off:
    dependencies: [ ]
    file: ceph.conf
    section: [ global ]
    values:
      bluestore codel: false
  mclock:
    dependencies: [ ]
    file: ceph.conf
    section: [ global ]
    values:
      osd op queue: mclock_scheduler
      osd mclock skip benchmark: true
  wpq:
    dependencies: [ ]
    file: ceph.conf
    section: [ global ]
    values:
      osd op queue: wpq
  mclock_client_profile:
    dependencies: [ ]
    file: ceph.conf
    section: [ global ]
    values:
      osd mclock scheduler client res: { 0 }
      osd mclock scheduler client wgt: { 1 }
      osd mclock scheduler client lim: { 2 }
  mclock_profile:
    dependencies: [ ]
    file: ceph.conf
    section: [ global ]
    values:
      osd mclock profile: { 0 }
  mclock_recov_profile:
    dependencies: [ ]
    file: ceph.conf
    section: [ global ]
    values:
      osd mclock scheduler background recovery res: { 0 }
      osd mclock scheduler background recovery wgt: { 1 }
      osd mclock scheduler background recovery lim: { 2 }
  sharding_off:
    dependencies: [ ]
    file: ceph.conf
    section: [ global ]
    values:
      osd op num shards: 1
  sharding_on:
    dependencies: [ ]
    file: ceph.conf
    section: [ global ]
    values:
      osd op num shards: { 0 }
  throttle_off:
    dependencies: [ ]
    file: ceph.conf
    section: [ global ]
    values:
      bluestore throttle bytes: 10240Mi
      bluestore throttle deferred_bytes: 10240Mi
  throttle_on:
    dependencies: [ ]
    file: ceph.conf
    section: [ global ]
    values:
      bluestore throttle bytes: { 0 }
      bluestore throttle deferred_bytes: { 0 }
  fio:
    dependencies: [ ]
    file: cbt.yaml
    section: [ benchmarks, fio ]
    values:
      op_size: { 0 }
      iodepth: { 1 }
  fio_burst:
    dependencies: [ ]
    file: cbt.yaml
    section: [ benchmarks, fio, extra_config ]
    values:
      thinktime: { 0 }
      thinktime_blocks: { 1 }
      iodepth_low: 0
      iodepth_batch_submit: 0
      iodepth_batch_complete_min: 1
      iodepth_batch_complete_max: { 1 }
  recovery_on:
    dependencies: [ ]
    file: cbt.yaml
    section: [ cluster, recovery_test ]
    values:
      osds: [ 1 ]
  recovery_size:
    dependencies: [ ]
    file: ceph.conf
    section: [ global ]
    values:
      osd recovery max chunk: { 0 }
  fio_dynamic_bs:
    dependencies: [  ]
    file: cbt_dynamic.yaml
    out: cbt.yaml
    section: [ benchmarks, fio ]
    values:
      fio_conf: ~/Ceph-mClock-benchmark/benchmark/dynamic_bs.fio
  fio_dynamic_iodepth:
    dependencies: [  ]
    file: cbt_dynamic.yaml
    out: cbt.yaml
    section: [ benchmarks, fio ]
    values:
      fio_conf: ~/Ceph-mClock-benchmark/benchmark/dynamic_iodepth.fio
  fio_file:
    dependencies: [  ]
    file: cbt_dynamic.yaml
    out: cbt.yaml
    section: [ benchmarks, fio ]
    values:
      fio_conf: { 0 }
  fio_rw:
    dependencies: [ ]
    file: cbt.yaml
    out: cbt.yaml
    section: [ benchmarks, fio ]
    values:
      mode: randrw
      op_size: { 0 }
      iodepth: { 1 }
      rwmixread: { 2 }
  fio_mixed_write:
    dependencies: [ ]
    file: cbt_multi_write.yaml
    out: cbt.yaml
    section: [ benchmarks, fio ]
    values:
      bssplit: { 0 }
      iodepth: { 1 }
  fio_read:
    dependencies: [ ]
    file: cbt.yaml
    section: [ benchmarks, fio ]
    values:
      mode: randread
      op_size: { 0 }
      iodepth: { 1 }
  poisson_rate:
    dependencies: [ ]
    file: cbt.yaml
    section: [ benchmarks, fio, extra_config ]
    values:
      rate_process: poisson
