variables:
  throttle_bytes: 512Ki

benchmarks:
  # 4k 64 burst write
  - name: static_512k_4k_64_burst_recov
    configs:
      - name: codel_off
        params: [ ]
      - name: mclock
        params: [ ]
      - name: sharding_off
        params: [ ]
      - name: mclock_client_profile
        params: [ $client_iops, $client_wgt, $client_limit ]
      - name: mclock_recov_profile
        params: [ $recovery_iops, $recovery_wgt, $recovery_limit ]
      - name: throttle_on
        params: [ $throttle_bytes ]
      - name: fio
        params: [ 4Ki, 64 ]
      - name: fio_burst
        params: [ $burst_time, 64 ]
      - name: recovery_on
        params: [ ]
      - name: recovery_size
        params: [ 300Ki ]
  # 32k 64 burst write
  - name: static_512k_32k_64_burst_recov
    configs:
      - name: codel_off
        params: [ ]
      - name: mclock
        params: [ ]
      - name: sharding_off
        params: [ ]
      - name: mclock_client_profile
        params: [ $client_iops, $client_wgt, $client_limit ]
      - name: mclock_recov_profile
        params: [ $recovery_iops, $recovery_wgt, $recovery_limit ]
      - name: throttle_on
        params: [ $throttle_bytes ]
      - name: fio
        params: [ 32Ki, 64 ]
      - name: fio_burst
        params: [ $burst_time, 64 ]
      - name: recovery_on
        params: [ ]
      - name: recovery_size
        params: [ 300Ki ]
  # 4k 64 regular write
  - name: static_512k_4k_64_reg_recov
    configs:
      - name: codel_off
        params: [ ]
      - name: mclock
        params: [ ]
      - name: sharding_off
        params: [ ]
      - name: mclock_client_profile
        params: [ $client_iops, $client_wgt, $client_limit ]
      - name: mclock_recov_profile
        params: [ $recovery_iops, $recovery_wgt, $recovery_limit ]
      - name: throttle_on
        params: [ $throttle_bytes ]
      - name: fio
        params: [ 4Ki, 64 ]
      - name: recovery_on
        params: [ ]
      - name: recovery_size
        params: [ 300Ki ]
  # 32k 64 regular write
  - name: static_512k_32k_64_reg_recov
    configs:
      - name: codel_off
        params: [ ]
      - name: mclock
        params: [ ]
      - name: sharding_off
        params: [ ]
      - name: mclock_client_profile
        params: [ $client_iops, $client_wgt, $client_limit ]
      - name: mclock_recov_profile
        params: [ $recovery_iops, $recovery_wgt, $recovery_limit ]
      - name: throttle_on
        params: [ $throttle_bytes ]
      - name: fio
        params: [ 32Ki, 64 ]
      - name: recovery_on
        params: [ ]
      - name: recovery_size
        params: [ 300Ki ]
  # 4k 64 regular read
  - name: static_512k_4k_64_read_recov
    configs:
      - name: codel_off
        params: [ ]
      - name: mclock
        params: [ ]
      - name: sharding_off
        params: [ ]
      - name: mclock_client_profile
        params: [ $client_iops, $client_wgt, $client_limit ]
      - name: mclock_recov_profile
        params: [ $recovery_iops, $recovery_wgt, $recovery_limit ]
      - name: throttle_on
        params: [ $throttle_bytes ]
      - name: fio_read
        params: [ 4Ki, 64 ]
      - name: recovery_on
        params: [ ]
      - name: recovery_size
        params: [ 300Ki ]
  # 32k 64 regular read
  - name: static_512k_32k_64_read_recov
    configs:
      - name: codel_off
        params: [ ]
      - name: mclock
        params: [ ]
      - name: sharding_off
        params: [ ]
      - name: mclock_client_profile
        params: [ $client_iops, $client_wgt, $client_limit ]
      - name: mclock_recov_profile
        params: [ $recovery_iops, $recovery_wgt, $recovery_limit ]
      - name: throttle_on
        params: [ $throttle_bytes ]
      - name: fio_read
        params: [ 32Ki, 64 ]
      - name: recovery_on
        params: [ ]
      - name: recovery_size
        params: [ 300Ki ]
  # 4k 64 25% write
  - name: static_512k_4k_64_25_write_recov
    configs:
      - name: codel_off
        params: [ ]
      - name: mclock
        params: [ ]
      - name: sharding_off
        params: [ ]
      - name: mclock_client_profile
        params: [ $client_iops, $client_wgt, $client_limit ]
      - name: mclock_recov_profile
        params: [ $recovery_iops, $recovery_wgt, $recovery_limit ]
      - name: throttle_on
        params: [ $throttle_bytes ]
      - name: fio_rw
        params: [ 4Ki, 64, 75 ]
      - name: recovery_on
        params: [ ]
      - name: recovery_size
        params: [ 300Ki ]
  # 32k 64 25% write
  - name: static_512k_32k_64_25_write_recov
    configs:
      - name: codel_off
        params: [ ]
      - name: mclock
        params: [ ]
      - name: sharding_off
        params: [ ]
      - name: mclock_client_profile
        params: [ $client_iops, $client_wgt, $client_limit ]
      - name: mclock_recov_profile
        params: [ $recovery_iops, $recovery_wgt, $recovery_limit ]
      - name: throttle_on
        params: [ $throttle_bytes ]
      - name: fio_rw
        params: [ 32Ki, 64, 75 ]
      - name: recovery_on
        params: [ ]
      - name: recovery_size
        params: [ 300Ki ]
  # 4k 64 50% write
  - name: static_512k_4k_64_50_write_recov
    configs:
      - name: codel_off
        params: [ ]
      - name: mclock
        params: [ ]
      - name: sharding_off
        params: [ ]
      - name: mclock_client_profile
        params: [ $client_iops, $client_wgt, $client_limit ]
      - name: mclock_recov_profile
        params: [ $recovery_iops, $recovery_wgt, $recovery_limit ]
      - name: throttle_on
        params: [ $throttle_bytes ]
      - name: fio_rw
        params: [ 4Ki, 64, 50 ]
      - name: recovery_on
        params: [ ]
      - name: recovery_size
        params: [ 300Ki ]
  # 32k 64 50% write
  - name: static_512k_32k_64_50_write_recov
    configs:
      - name: codel_off
        params: [ ]
      - name: mclock
        params: [ ]
      - name: sharding_off
        params: [ ]
      - name: mclock_client_profile
        params: [ $client_iops, $client_wgt, $client_limit ]
      - name: mclock_recov_profile
        params: [ $recovery_iops, $recovery_wgt, $recovery_limit ]
      - name: throttle_on
        params: [ $throttle_bytes ]
      - name: fio_rw
        params: [ 32Ki, 64, 50 ]
      - name: recovery_on
        params: [ ]
      - name: recovery_size
        params: [ 300Ki ]
  # 4k 64 75% write
  - name: static_512k_4k_64_75_write_recov
    configs:
      - name: codel_off
        params: [ ]
      - name: mclock
        params: [ ]
      - name: sharding_off
        params: [ ]
      - name: mclock_client_profile
        params: [ $client_iops, $client_wgt, $client_limit ]
      - name: mclock_recov_profile
        params: [ $recovery_iops, $recovery_wgt, $recovery_limit ]
      - name: throttle_on
        params: [ $throttle_bytes ]
      - name: fio_rw
        params: [ 4Ki, 64, 25 ]
      - name: recovery_on
        params: [ ]
      - name: recovery_size
        params: [ 300Ki ]
  # 32k 64 75% write
  - name: static_512k_32k_64_75_write_recov
    configs:
      - name: codel_off
        params: [ ]
      - name: mclock
        params: [ ]
      - name: sharding_off
        params: [ ]
      - name: mclock_client_profile
        params: [ $client_iops, $client_wgt, $client_limit ]
      - name: mclock_recov_profile
        params: [ $recovery_iops, $recovery_wgt, $recovery_limit ]
      - name: throttle_on
        params: [ $throttle_bytes ]
      - name: fio_rw
        params: [ 32Ki, 64, 25 ]
      - name: recovery_on
        params: [ ]
      - name: recovery_size
        params: [ 300Ki ]
